server:
  servlet:
    context-path: /EmpGuid
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/empguid?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
logging:
  level:
    com.*: debug 
mybatis:
  mapper-locations:
  - classpath:/mapper/**/*.xml 
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql